name = "costco-deals-tracker"
main = "src/index.ts"
compatibility_date = "2025-08-08"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"

# KV namespace bindings for development (top-level default)
kv_namespaces = [
  { binding = "DEAL_WATCHER", id = "f060b6ab17da4e43a168e44da8744a04", preview_id = "f060b6ab17da4e43a168e44da8744a04" }
]

# Cron trigger - runs every 3 hours
[triggers]
crons = ["0 */3 * * *"]

# Production environment configuration
[env.production]
kv_namespaces = [
  { binding = "DEAL_WATCHER", id = "1e887257efa04d869bcd10443ab855ee" }
]

# Development environment configuration
[env.development]
kv_namespaces = [
  { binding = "DEAL_WATCHER", id = "f060b6ab17da4e43a168e44da8744a04" }
]

# Environment variables (set via wrangler secret put)
# These are configured as secrets for security:
# - ADMIN_TOKEN: Authentication token for admin endpoints
# - SLACK_WEBHOOK: Slack webhook URL for notifications